apiVersion: v1
kind: Service
metadata:
  name: spring_boot_app_service
spec:
  selector:
    app: spring_boot_app
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080 