pipeline {
    agent { label 'JENKINS_SLAVE' }
    stages {
        stage('Git Checkout') {
            steps {
                sh 'echo passed'
            }
        }
        stage('Build and Test') {
            steps{
                sh 'cd Complete_CICD && mvn clean package'
                archiveArtifacts artifacts: '**/target/*.jar', followSymlinks: false
            }
        }
        stage('Static code Analysis') {
            environment {
                SONAR_URL = "http://34.125.186.140:9000"
            }
            steps {
                withCredentials([string(credentialsId: 'SONAR_TOKEN', variable: 'SONAR_AUTH_TOKEN')]) {
                    sh 'cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=${SONAR_URL}'
                }
            }
        }
    }
}