pipeline {
    agent { label 'jdk_17'}
    triggers {
        pollSCM('* * * * *')
    }
    stages {
        stage('Version Control') {
            steps {
                git url: 'https://github.com/saivamsipranay/spring-petclinic.git', branch: "main"
            }
        }
        stage('Build') {
            steps {
                sh 'mvn package'
            }
        }
        stage('Test and Artifact') {
            steps {
                junit '**/surefire-reports/TEST-*.xml'
                archiveArtifacts artifacts: '**/target/*.jar', followSymlinks: false
            }
        }
        stage('Deploy') {
            steps {
                sh "java -jar target/*.jar"
            }
        }
    }
    post {
        success {
            mail subject: "jenkins build of ${JOB_NAME} with id ${BUILD_NUMBER} is successfull", 
                 body: "use this url ${BUILD_URL} for more info.",
                 from: 'devops_pipeline.com',
                 to: "team-all@svp.com"
        }
        failure {
            mail subject: "jenkins build of ${JOB_NAME} with id ${BUILD_NUMBER} is failed",
                body: "use this url ${BUILD_URL} for more info.",
                from: 'devops_pipeline.com',
                to: "${GIT_COMMITTER_EMAIL}"
        }

    }
}