pipeline {
    agent { label 'jdk_17'}
    triggers {pollSCM('* * * * *')} 
    stages {
        stage('vcs') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/khajadevopsmarch23/MusicStore.git'
            }
        }
        stage('Build') {
            steps {
                sh 'dotnet restore ./MusicStore/MusicStore.csproj && dotnet build ./MusicStore/MusicStore.csproj'
            }
        }
        stage('Test') {
            steps {
                sh 'dotnet test --logger "junit;LogFilePath=TEST-musicstoretest.xml" ./MusicStore/MusicStore.csproj'
                junit testResults : '**/TEST-*.xml'
            }
        }
    }
}