pipeline {
    agent { label 'jdk_17'}
    triggers {
        pollSCM('* * * * *')
    }
    stages {
        stage('Version Control') {
            steps {
                git url: 'https://github.com/saivamsipranay/spring-petclinic.git', branch: "main"
            }
        }
        stage('Build') {
            steps {
                sh 'mvn package'
            }
        }
        stage('Test and Artifacts') {
            steps {
                junit '**/surefire-reports/TEST-*.xml'
                archiveArtifacts artifacts: '**/target/*.jar', followSymlinks: false
            }
        }
        stage('Deploy') {
            steps {
                sh "java -jar target/*.jar"
            }
        }
    }
}