pipeline {
    agent { label 'jdk_17'}
    triggers {
        pollSCM('* * * * *')
    }
    stages {
        stage('git') {
            steps {
                git url: 'https://github.com/saivamsipranay/spring-petclinic.git', branch: "main"
            }
        }
        stage('build') {
            steps {
                sh 'mvn package'
            }
        }
    }
}